
import java.awt.Color;
import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.JFrame;


public class Main extends javax.swing.JFrame {
    
    private void getData(){
    
        String nombre=jTextField_nombre.getText();
        String telefono=jTextField_telefono.getText();
        String hamburguesa, papas, gaseosa;
        ArrayList <String> condimentos = new ArrayList<>();

        
        //HAMBURGUESAS**********************
        if(hamb_chica.isSelected()){
            hamburguesa="Pequeña";
        }else if(hamb_mediana.isSelected()){
            hamburguesa="Mediana";            
        }else{
            hamburguesa="Grandes";            
        }
        
        //PAPAS****************************
        if(papas_chicas.isSelected()){
            papas="Pequeñas";
        }else{
            papas="Grendes";
        }
        
        //GASEOSAS ************************
        if(jRadioB_cocaCola.isSelected()){
            gaseosa=jRadioB_cocaCola.getText();
        }else if(jRadioB_sprite.isSelected()){
            gaseosa=jRadioB_sprite.getText();
        }else{
            gaseosa=jRadioB_fanta.getText();
        }
        
        //CONDIMENTOS*********************
        if(jLabel_cebolla.isSelected()){
            condimentos.add(jLabel_cebolla.getText());
        }
        if(jLabel_lechuga.isSelected()){
            condimentos.add(jLabel_lechuga.getText());
        }
        if(jLabel_panceta.isSelected()){
            condimentos.add(jLabel_panceta.getText());
        }
        if(jLabel_pepino.isSelected()){
            condimentos.add(jLabel_pepino.getText());
        }
        if(jLabel_pikles.isSelected()){
            condimentos.add(jLabel_pikles.getText());
        }
        if(jLabel_tomate.isSelected()){
            condimentos.add(jLabel_tomate.getText());
        }
        
        
        Pedidos pedidos = new Pedidos(nombre,telefono,hamburguesa,papas,gaseosa,condimentos);
        pedidos.imprimir();
        UIPedidos uip = new UIPedidos(pedidos);

        
        this.setVisible(false);
        uip.setVisible(true);
    }
    
    private void limpiarVentana(){
        hamb_chica.setSelected(true);
        papas_chicas.setSelected(true);
        jRadioB_cocaCola.setSelected(true);
        
        hamb_mediana.setSelected(false);
        hamb_grande.setSelected(false);
        papas_grandes.setSelected(false);
        jRadioB_sprite.setSelected(false);
        jRadioB_fanta.setSelected(false);
        jLabel_cebolla.setSelected(false);
        jLabel_lechuga.setSelected(false);
        jLabel_panceta.setSelected(false);
        jLabel_pepino.setSelected(false);
        jLabel_pikles.setSelected(false);
        jLabel_tomate.setSelected(false);
    }
    
    

    public Main() {
        initComponents();
        this.setTitle("Hamburguesería");
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.getContentPane().setBackground(Color.white);               
        hamb_chica.setSelected(true);
        papas_chicas.setSelected(true);
        jRadioB_cocaCola.setSelected(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel_datos = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_nombre = new javax.swing.JTextField();
        jTextField_telefono = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel_cebolla = new javax.swing.JCheckBox();
        jLabel_lechuga = new javax.swing.JCheckBox();
        jLabel_panceta = new javax.swing.JCheckBox();
        pepino = new javax.swing.JLabel();
        picle = new javax.swing.JLabel();
        tomate = new javax.swing.JLabel();
        jLabel_pepino = new javax.swing.JCheckBox();
        jLabel_pikles = new javax.swing.JCheckBox();
        jLabel_tomate = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        hamb_chica = new javax.swing.JRadioButton();
        hamb_mediana = new javax.swing.JRadioButton();
        hamb_grande = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        papas_chicas = new javax.swing.JRadioButton();
        papas_grandes = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel_sprite = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jRadioB_cocaCola = new javax.swing.JRadioButton();
        jRadioB_sprite = new javax.swing.JRadioButton();
        jRadioB_fanta = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jButton_limpiar = new javax.swing.JButton();
        jButton_pedir = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/hamburgesa.jpg"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LA HAMBURGUESERIA");
        jLabel2.setAlignmentY(0.0F);
        jLabel2.setOpaque(true);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("HORA");
        jLabel3.setAlignmentY(0.0F);
        jLabel3.setOpaque(true);

        jPanel_datos.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_datos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel_datos.setAlignmentX(0.0F);
        jPanel_datos.setAlignmentY(0.0F);
        jPanel_datos.setLayout(new java.awt.GridBagLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Nombre: ");
        jLabel4.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 113;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 158, 0, 0);
        jPanel_datos.add(jLabel4, gridBagConstraints);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Telefono: ");
        jLabel5.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 113;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 158, 0, 0);
        jPanel_datos.add(jLabel5, gridBagConstraints);

        jTextField_nombre.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 219;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 65, 0, 243);
        jPanel_datos.add(jTextField_nombre, gridBagConstraints);

        jTextField_telefono.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 219;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 65, 9, 243);
        jPanel_datos.add(jTextField_telefono, gridBagConstraints);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jPanel_datos, javax.swing.GroupLayout.PREFERRED_SIZE, 905, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_datos, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        jPanel4.setLayout(new java.awt.GridLayout(4, 3));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cebolla.jpg"))); // NOI18N
        jPanel4.add(jLabel6);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lechuga.jpg"))); // NOI18N
        jPanel4.add(jLabel9);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/panceta.jpg"))); // NOI18N
        jPanel4.add(jLabel10);

        jLabel_cebolla.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_cebolla.setText("CEBOLLA");
        jLabel_cebolla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_cebolla.setOpaque(true);
        jLabel_cebolla.setPreferredSize(new java.awt.Dimension(84, 10));
        jLabel_cebolla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLabel_cebollaActionPerformed(evt);
            }
        });
        jPanel4.add(jLabel_cebolla);

        jLabel_lechuga.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_lechuga.setText("LECHUGA");
        jLabel_lechuga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_lechuga.setOpaque(true);
        jLabel_lechuga.setPreferredSize(new java.awt.Dimension(84, 10));
        jPanel4.add(jLabel_lechuga);

        jLabel_panceta.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_panceta.setText("PANCETA");
        jLabel_panceta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_panceta.setOpaque(true);
        jLabel_panceta.setPreferredSize(new java.awt.Dimension(84, 10));
        jPanel4.add(jLabel_panceta);

        pepino.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pepino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pepino.jpg"))); // NOI18N
        jPanel4.add(pepino);

        picle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        picle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pikles.jpg"))); // NOI18N
        jPanel4.add(picle);

        tomate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tomate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tomates.jpg"))); // NOI18N
        jPanel4.add(tomate);

        jLabel_pepino.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_pepino.setText("PEPINOS");
        jLabel_pepino.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_pepino.setOpaque(true);
        jLabel_pepino.setPreferredSize(new java.awt.Dimension(84, 10));
        jLabel_pepino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLabel_pepinoActionPerformed(evt);
            }
        });
        jPanel4.add(jLabel_pepino);

        jLabel_pikles.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_pikles.setText("PIKLES");
        jLabel_pikles.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_pikles.setOpaque(true);
        jLabel_pikles.setPreferredSize(new java.awt.Dimension(84, 10));
        jPanel4.add(jLabel_pikles);

        jLabel_tomate.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_tomate.setText("TOMATE");
        jLabel_tomate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_tomate.setOpaque(true);
        jLabel_tomate.setPreferredSize(new java.awt.Dimension(84, 10));
        jPanel4.add(jLabel_tomate);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel14.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Elegí tus condimentos");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));

        hamb_chica.setBackground(new java.awt.Color(255, 255, 255));
        hamb_chica.setText("CHICAS");
        hamb_chica.setOpaque(true);
        hamb_chica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hamb_chicaActionPerformed(evt);
            }
        });
        jPanel5.add(hamb_chica);

        hamb_mediana.setBackground(new java.awt.Color(255, 255, 255));
        hamb_mediana.setText("MEDIANAS");
        hamb_mediana.setOpaque(true);
        hamb_mediana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hamb_medianaActionPerformed(evt);
            }
        });
        jPanel5.add(hamb_mediana);

        hamb_grande.setBackground(new java.awt.Color(255, 255, 255));
        hamb_grande.setText("GRANDES");
        hamb_grande.setOpaque(true);
        hamb_grande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hamb_grandeActionPerformed(evt);
            }
        });
        jPanel5.add(hamb_grande);

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Elegí el tamaño de la hamburguesa");

        jLabel15.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Elegí el tamaño de tus papas.");

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 1, 2);
        flowLayout1.setAlignOnBaseline(true);
        jPanel6.setLayout(flowLayout1);

        papas_chicas.setBackground(new java.awt.Color(255, 255, 255));
        papas_chicas.setText("CHICAS");
        papas_chicas.setOpaque(true);
        papas_chicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                papas_chicasActionPerformed(evt);
            }
        });
        jPanel6.add(papas_chicas);

        papas_grandes.setBackground(new java.awt.Color(255, 255, 255));
        papas_grandes.setText("GRANDES");
        papas_grandes.setOpaque(true);
        papas_grandes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                papas_grandesActionPerformed(evt);
            }
        });
        jPanel6.add(papas_grandes);

        jPanel7.setLayout(new java.awt.GridLayout(2, 3));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cocaCola.jpg"))); // NOI18N
        jLabel16.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel16.setOpaque(true);
        jPanel7.add(jLabel16);

        jLabel_sprite.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_sprite.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_sprite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sprite.png"))); // NOI18N
        jLabel_sprite.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel_sprite.setOpaque(true);
        jPanel7.add(jLabel_sprite);

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fanta.jpg"))); // NOI18N
        jLabel17.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel17.setOpaque(true);
        jPanel7.add(jLabel17);

        jRadioB_cocaCola.setBackground(new java.awt.Color(255, 255, 255));
        jRadioB_cocaCola.setText("COCA COLA");
        jRadioB_cocaCola.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioB_cocaCola.setOpaque(true);
        jRadioB_cocaCola.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jRadioB_cocaCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioB_cocaColaActionPerformed(evt);
            }
        });
        jPanel7.add(jRadioB_cocaCola);

        jRadioB_sprite.setBackground(new java.awt.Color(255, 255, 255));
        jRadioB_sprite.setText("SPRITE");
        jRadioB_sprite.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioB_sprite.setOpaque(true);
        jRadioB_sprite.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jRadioB_sprite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioB_spriteActionPerformed(evt);
            }
        });
        jPanel7.add(jRadioB_sprite);

        jRadioB_fanta.setBackground(new java.awt.Color(255, 255, 255));
        jRadioB_fanta.setText("FANTA");
        jRadioB_fanta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRadioB_fanta.setOpaque(true);
        jRadioB_fanta.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jRadioB_fanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioB_fantaActionPerformed(evt);
            }
        });
        jPanel7.add(jRadioB_fanta);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Elegi tu gaseosa: ");

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jButton_limpiar.setBackground(new java.awt.Color(255, 255, 204));
        jButton_limpiar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_limpiar.setForeground(new java.awt.Color(255, 0, 51));
        jButton_limpiar.setText("LIMPIAR");
        jButton_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_limpiarActionPerformed(evt);
            }
        });

        jButton_pedir.setBackground(new java.awt.Color(255, 255, 204));
        jButton_pedir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_pedir.setForeground(new java.awt.Color(255, 0, 51));
        jButton_pedir.setText("PEDIR");
        jButton_pedir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_pedirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jButton_pedir, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_pedir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/hamburguesaLogo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(339, 339, 339)
                                        .addComponent(jLabel12))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE))))
                                .addGap(18, 18, 18)
                                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(111, 111, 111))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addGap(10, 10, 10)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(425, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(218, 218, 218))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_cebollaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLabel_cebollaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_cebollaActionPerformed

    private void jLabel_pepinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLabel_pepinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_pepinoActionPerformed

    private void jButton_pedirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_pedirActionPerformed
        getData();
       // cerrarVentana();
        
    }//GEN-LAST:event_jButton_pedirActionPerformed

    private void hamb_chicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hamb_chicaActionPerformed
        if(hamb_chica.isSelected()){
            hamb_mediana.setSelected(false);
            hamb_grande.setSelected(false);
        }
    }//GEN-LAST:event_hamb_chicaActionPerformed

    private void hamb_medianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hamb_medianaActionPerformed
        if(hamb_mediana.isSelected()){
            hamb_chica.setSelected(false);
            hamb_grande.setSelected(false);
        }
    }//GEN-LAST:event_hamb_medianaActionPerformed

    private void hamb_grandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hamb_grandeActionPerformed
        if(hamb_grande.isSelected()){
            hamb_chica.setSelected(false);
            hamb_mediana.setSelected(false);
        }
    }//GEN-LAST:event_hamb_grandeActionPerformed

    private void papas_chicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_papas_chicasActionPerformed
        if(papas_chicas.isSelected()){
            papas_grandes.setSelected(false);
        }
    }//GEN-LAST:event_papas_chicasActionPerformed

    private void papas_grandesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_papas_grandesActionPerformed
        if(papas_grandes.isSelected()){
            papas_chicas.setSelected(false);
        }
    }//GEN-LAST:event_papas_grandesActionPerformed

    private void jRadioB_cocaColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioB_cocaColaActionPerformed
        if(jRadioB_cocaCola.isSelected()){
            jRadioB_fanta.setSelected(false);
            jRadioB_sprite.setSelected(false);
        }
    }//GEN-LAST:event_jRadioB_cocaColaActionPerformed

    private void jRadioB_spriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioB_spriteActionPerformed
        if(jRadioB_sprite.isSelected()){
            jRadioB_cocaCola.setSelected(false);
            jRadioB_fanta.setSelected(false);
        }
    }//GEN-LAST:event_jRadioB_spriteActionPerformed

    private void jRadioB_fantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioB_fantaActionPerformed
        if(jRadioB_fanta.isSelected()){
            jRadioB_cocaCola.setSelected(false);
            jRadioB_sprite.setSelected(false);
        }
    }//GEN-LAST:event_jRadioB_fantaActionPerformed

    private void jButton_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_limpiarActionPerformed
        limpiarVentana();        
    }//GEN-LAST:event_jButton_limpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton hamb_chica;
    private javax.swing.JRadioButton hamb_grande;
    private javax.swing.JRadioButton hamb_mediana;
    private javax.swing.JButton jButton_limpiar;
    private javax.swing.JButton jButton_pedir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JCheckBox jLabel_cebolla;
    private javax.swing.JCheckBox jLabel_lechuga;
    private javax.swing.JCheckBox jLabel_panceta;
    private javax.swing.JCheckBox jLabel_pepino;
    private javax.swing.JCheckBox jLabel_pikles;
    private javax.swing.JLabel jLabel_sprite;
    private javax.swing.JCheckBox jLabel_tomate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanel_datos;
    private javax.swing.JRadioButton jRadioB_cocaCola;
    private javax.swing.JRadioButton jRadioB_fanta;
    private javax.swing.JRadioButton jRadioB_sprite;
    private javax.swing.JTextField jTextField_nombre;
    private javax.swing.JTextField jTextField_telefono;
    private javax.swing.JRadioButton papas_chicas;
    private javax.swing.JRadioButton papas_grandes;
    private javax.swing.JLabel pepino;
    private javax.swing.JLabel picle;
    private javax.swing.JLabel tomate;
    // End of variables declaration//GEN-END:variables
}
